### ISSUE TITLE
missing ", out result"

### ISSUE THREAD

**Issue by DickBaker** [VerifyTests/EmptyFiles#103]
the file test.cs line 110 should read
Assert.False(AllFiles.TryGetPathFor("foo.txt", out result));

**Comment by DickBaker** [comment]
For test.cs read tests.cs (whoops!)

**Comment by SimonCropp** [comment]
line 110 is 
```
Assert.False(AllFiles.TryCreateFile...
```
not 
```
Assert.False(AllFiles.TryGetPathFor...
```

**Comment by DickBaker** [comment]
EmptyFiles/src/EmptyFiles.Tests/tests.cs sorry I should have given absolute path
If param missing it makes a mockery of the following line 111 that tests result

**Comment by SimonCropp** [comment]
can you submit a pull request that illustrates the change you are proposing

**Comment by SimonCropp** [comment]
bump
