### ISSUE TITLE
Specify size for load tests

### ISSUE THREAD

**Issue by tomap** [VerifyTests/EmptyFiles#180]
I need to do a load test, where I already have a set of "real" files which I would like to mock

I thought this set of empty files would be perfect to do that, except they have a "small" fixed size

It would be awesome if we could specify a size so that the  file would be appended with dummy data

The issue with this solution is that it can work easily for text based files, but might be much more complex for binary file, and needs to be "custom tailored" for each types of file

Maybe there is a better solution for this feature?

Thank you

**Comment by SimonCropp** [comment]
sorry. but i think that is out of scope for this project.

happy for you to use any code from this project in creating your own project
